### ISSUE TITLE
Binary reference sequence ids/names in gtf output

### ISSUE THREAD

**Issue by petersbr** [ruolin/strawberry#12]
Hello,

I have been trying to move to the updated version of strawberry.  The pre-compiled version runs but produces a gtf file called assembled_transcripts.gtf.  Unfortunately, that gtf file is unusable because the chromosome names are binary instead of text.

I have not been able to see if this is corrected in a self-compiled version of the git code because that version segfaults on real data leading me to suspect that I didn't get the right versions of the external headers and libraries that it needs.

Could you fix the binary names issue in the precompiled version? 

Thanks!
Brooke P-B

**Comment by ruolin** [comment]
Hi @petersbr, thanks for your comments. 
I have some bug fixes to version 0.9.0. Some one also points that when Strawberry runs on tophat2 alignment, it produces segfaults? What aligner are you using? Also, I have some important bug fixes that have been done to version 0.9.0. And I just updated the binary. 

But for the other issue you reported, I have never seen binary chrom names before. Could you share with your bam file? maybe just for a gene? So I can test a little bit. I also put a small test case, a single bam sample consisted of reads from 300 genes in a folder called example.

**Comment by petersbr** [comment]
I am working with hisat2 v2.1.0 to generate BAM files.  I can reproduce the problem in runs where it occurs.  It was observed in approximately 7% of my runs.  In affected GTF output files, only the refseq column is binary, all other gtf columns are fine.  I'll see if I can figure out how to create a small test bam that will reproduce the problem.

**Comment by petersbr** [comment]
I haven't yet had luck with subsets of the bam file but I can regularly reproduce the issue on full hisat bam files, but only those from a given genome.  The only thing that is different about the reference sequences is their naming scheme.  Instead of a simple Chr1 which is working ok in a genome named that way, in the genome where they have names like Chr01_AB12C_PacBio seems to put binary objects in place of the reference name column in the GTF.  I haven't tested yet by renaming and re-mapping, but I'm hoping this might suggest a potential cause to you.

**Comment by ruolin** [comment]
@petersbr thanks. I think you have enough information for me now. I will try to fix this problem and let you know. I have been swamped by my defense next week. So I will probably push the fix two weeks later. At the mean time, if you could just print a first few line of you problematic bam file (plus the header) and upload as a text file here, it would be a great help to me.

**Comment by petersbr** [comment]
test$ samtools view -h ../mapped_assembly_input_reads.bam | head -n 25
@HD     VN:1.0  SO:coordinate
@SQ     SN:Chr01_AB12C_PacBio   LN:311861409
@SQ     SN:Chr02_AB12C_PacBio   LN:245893436
@SQ     SN:Chr03_AB12C_PacBio   LN:237154059
@SQ     SN:Chr04_AB12C_PacBio   LN:251543118
@SQ     SN:Chr05_AB12C_PacBio   LN:220160916
@SQ     SN:Chr06_AB12C_PacBio   LN:171921718
@SQ     SN:Chr07_AB12C_PacBio   LN:182734546
@SQ     SN:Chr08_AB12C_PacBio   LN:178900968
@SQ     SN:Chr09_AB12C_PacBio   LN:164035347
@SQ     SN:Chr10_AB12C_PacBio   LN:151692717
@SQ     SN:Chr00_AB12C_PacBio   LN:45283500
@PG     ID:hisat2       PN:hisat2       VN:2.1.0        CL:"/bin/hisat2-align-s --wrapper basic-0 -p 10 --dta --maxins 880 -q --downstream-transcriptome-assembly -x align_reads/ref_seq -1 AB12C.trimmed.r1.fastq -2 AB12C.trimmed.r2.fastq"
4864004 419     Chr01_AB12C_PacBio      7585    1       95M     =       47055   39564   AGCCTTCGGTATTATTGAAAATAGTCGTTCATGGCTATTTTCGACAAAAATGGGGGTTGTGTGGCCATTGATCATCGACCAGACGCTCATACACC CBCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG       AS:i:-5 ZS:i:-5 XN:i:0  XM:i:1  XO:i:0  XG:i:0  NM:i:1  MD:Z:8A86       YS:i:0  YT:Z:CP NH:i:3
13686472        355     Chr01_AB12C_PacBio      7594    1       1S93M   =       47045   39547   GTATTATTGAAAATAGTCGTTCATGGCTATTTTCGACAAAAATGGGGGTTGTGTGGCCATTGATCATCGACCAGACGCTCATACACCTCACCCC
        CCCGGGGGFGGGGGGGGGGGGGGGG>GGGGGGGGGGGGGGGGGGGGGGCEGGDGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG  AS:i:-1 ZS:i:-1 XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:93 YS:i:0  YT:Z:CP NH:i:5
29752673        419     Chr01_AB12C_PacBio      7594    1       4S91M   =       45144   37649   TCGGTATTATTGAAAATAGTCGTTCATGGCTATTTTCGACAAAAATGGGGGTTGTGTGGCCATTGATCATCGACCAGACGCTCATACACCTCACC       BBBGGGGGGGGGGGGGGGGGGGGGEGGGGGGGGGGGGGGGGGGGGGGGGFDEGGGGEGGGBGGGGEGEGGGEGGGGGGGGGBGGGGGGG=GGGGG AS:i:-4 ZS:i:-4 XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:91 YS:i:0  YT:Z:CP NH:i:4
32970675        99      Chr01_AB12C_PacBio      10626   1       95M     =       10649   118     AAGAATGAATTATAAGGAATACAAAGGTTTACATAGATAATTATACATTATTATTATATATAAATGGAAATAACATTGAATTACAAATGTACCTT       CCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGGGGGGGGGGGGGGGGGGGGGGGGGGGCGGGGGGFGD>GEFGGGGGGGGCGG00EC AS:i:0  ZS:i:0  XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:95 YS:i:-2 YT:Z:CP NH:i:4
32970675        355     Chr01_AB12C_PacBio      10626   1       95M     =       16903   6372    AAGAATGAATTATAAGGAATACAAAGGTTTACATAGATAATTATACATTATTATTATATATAAATGGAAATAACATTGAATTACAAATGTACCTT       CCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGGGGGGGGGGGGGGGGGGGGGGGGGGGCGGGGGGFGD>GEFGGGGGGGGCGG00EC AS:i:0  ZS:i:0  XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:95 YS:i:-2 YT:Z:CP NH:i:4
32970675        147     Chr01_AB12C_PacBio      10649   1       93M2S   =       10626   -118    AAGGTTTACATAGATAATTATACATTATTATTATATATAAATGGAAATAACATTGAATTACAAATGTACCTTCAACTTGAAGGAGATGAAAGTCC       :=0B>CGGCECGCFCGC1GGFF1F1@GEGGDE:1B<:111:1E:11GDB:@E1GGGF@E1F>11:1:<:1111CBGF;GBE1E1;1@;1111<03 AS:i:-2 ZS:i:-2 XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:93 YS:i:0  YT:Z:CP NH:i:4
32970675        355     Chr01_AB12C_PacBio      16880   1       95M     =       16903   118     AAGAATGAATTATAAGGAATACAAAGGTTTACATAGATAATTATACATTATTATTATATATAAATGGAAATAACATTGAATTACAAATGTACCTT       CCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGGGGGGGGGGGGGGGGGGGGGGGGGGGCGGGGGGFGD>GEFGGGGGGGGCGG00EC AS:i:0  ZS:i:0  XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:95 YS:i:-2 YT:Z:CP NH:i:4
32970675        403     Chr01_AB12C_PacBio      16903   1       93M2S   =       10626   -6372   AAGGTTTACATAGATAATTATACATTATTATTATATATAAATGGAAATAACATTGAATTACAAATGTACCTTCAACTTGAAGGAGATGAAAGTCC       :=0B>CGGCECGCFCGC1GGFF1F1@GEGGDE:1B<:111:1E:11GDB:@E1GGGF@E1F>11:1:<:1111CBGF;GBE1E1;1@;1111<03 AS:i:-2 ZS:i:-2 XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:93 YS:i:0  YT:Z:CP NH:i:4
32970675        403     Chr01_AB12C_PacBio      16903   1       93M2S   =       16880   -118    AAGGTTTACATAGATAATTATACATTATTATTATATATAAATGGAAATAACATTGAATTACAAATGTACCTTCAACTTGAAGGAGATGAAAGTCC       :=0B>CGGCECGCFCGC1GGFF1F1@GEGGDE:1B<:111:1E:11GDB:@E1GGGF@E1F>11:1:<:1111CBGF;GBE1E1;1@;1111<03 AS:i:-2 ZS:i:-2 XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:93 YS:i:0  YT:Z:CP NH:i:4
53159606        73      Chr01_AB12C_PacBio      25762   1       94M     =       25762   0       TTTGTCGAAAATAGCCATGAATGACCATTTTCAAAAATACCAAAGGCTAACACGTACGGATTTTTAACCAAGAAATGGTCTCCACCAGAAATCC
        ?0AGFG<=C/EGG11<CD1FDF11FFGGGGGDDB>10:=DG1:FGEEG>FGGGGGGGG</FBGGGC111=:0==EBCDF@@FGGGFG>B>00FC  AS:i:0  ZS:i:0  XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:94 YT:Z:UP NH:i:5
53159606        133     Chr01_AB12C_PacBio      25762   0       *       =       25762   0       AGAAGCTGATGGCTTTCGACCTTGATCAGTTTCTGGGGCACAGATCTGAGCTCTTGCTATCTCGTGGAGACCATTTCTTGGTTAACAATCCGTAC       <A01?11111111111@/0///111<11?F11?1111////>=G111111111>11<11=>F110>/=01=:C1CBED@000:000=BF00/:0/ YT:Z:UP
53159615        329     Chr01_AB12C_PacBio      25762   1       94M     =       25762   0       TTTGTCGAAAATAGCCATGAATGACCATTTTCAAAAATACCAAAGGCTAACACGTACGGATTTTTAACCAAGAAATGGTCTCCACCAGAAATCC
        CCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGGGGGGGGGGGFGGGGGGGGGGGGGGGEEFFDGGGGGGGFGGGGGGGG  AS:i:0  ZS:i:0  XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:94 YT:Z:UP NH:i:5

test$ samtools --version
samtools 1.1
Using htslib 1.1
Copyright (C) 2014 Genome Research Ltd.

**Comment by ruolin** [comment]
@petersbr Hello, 

I see no problem reading your file and convert to the right chrom names. see the log below.
Inspecting sample......
ref id: 0
 chr name: Chr01_AB12C_PacBio
ref id: 0
 chr name: Chr01_AB12C_PacBio
ref id: 0
 chr name: Chr01_AB12C_PacBio
ref id: 0
 chr name: Chr01_AB12C_PacBio
ref id: 0
 chr name: Chr01_AB12C_PacBio
ref id: 0
 chr name: Chr01_AB12C_PacBio
ref id: 0
 chr name: Chr01_AB12C_PacBio
ref id: 0
 chr name: Chr01_AB12C_PacBio
ref id: 0
 chr name: Chr01_AB12C_PacBio
ref id: 0
 chr name: Chr01_AB12C_PacBio
But your example contains only multimapped reads. so you need to have the switch --allow-multiple-his on.

**Comment by petersbr** [comment]
Thanks for looking into this issue.  If it cannot be reproduced, there really is nowhere to go further with this.

**Comment by ruolin** [comment]
@petersbr I think I finally found the bug that you were talking about and fixed it in version 0.9.1. Sorry I wasn't able to realize this issue early. For more information, see Nancy's Issue.

**Comment by petersbr** [comment]
Glad you found it!
