### ISSUE TITLE
Strawberry incompatible with STAR alignment output?

### ISSUE THREAD

**Issue by nancydongxyz** [ruolin/strawberry#14]
Hello!

I see in your recent paper that you decided not to use STAR as the aligner because it lacks the "XS" function. However, in my use of the most recent version of STAR, I can specify the "XS" option in the output. Am I interpreting this correctly?

I don't know if this is related, but when I tried Strawberry assembly of a few .bam files produced by STAR, I see in the **assembled_transcripts.gtf file** that there are a number of transcripts not allocated to scaffolds in my reference genome. When I tried to get the transcripts from the  **assembled_transcripts.gtf file** using `gffread`, I get only about 20% of the number of transcripts that I got from StringTie or Scallop.

It would really great if you can point out what could be going wrong. 

Thank you very much!

Nancy

**Comment by ruolin** [comment]
Hello @nancydongxyz. Thank you for posting the question. I would like to look into this problem. Is it possible for you to share one of the `.bam` file that you just described?

**Comment by nancydongxyz** [comment]
Hello Ruolin,

Here is the [link](https://utoronto-my.sharepoint.com/personal/nancy_dong_mail_utoronto_ca/_layouts/15/guestaccess.aspx?docid=0c8c50004deed4063b3dadf791dde7966&authkey=AevZrD-p73J_Nx5_rrZr5d4&expiration=2017-12-30T19%3A16%3A57.000Z&e=98183bf2f2ff4b9db0748ce2807b6932) to one of the BAM files that I had used with Strawberry. I used four BAM files, one for each pair-end RNA-seq library.

This is the command that I used to generate the BAM file (all four BAM files are generated using the same settings): 
`STAR --genomeDir ~/LS_genome_index_Nov14_GTF --runThreadN 8 --readFilesIn RNA-Seq_reads/AE_corrected_BYD_AEOSRB_7_1_HJLK5BBXX.12BA015_noribo_clean.cor.fq RNA-Seq_reads/AE_corrected_BYD_AEOSRB_7_2_HJLK5BBXX.12BA015_noribo_clean.cor.fq --outFileNamePrefix AE_corrected_filtered_Nov14_GTF_ref --seedPerReadNmax 10000 --sjdbGTFfile database/Genomes/LS/LS_GTF.gtf --sjdbOverhang 149 --twopassMode Basic --outReadsUnmapped Fastx --outSAMtype BAM SortedByCoordinate --outSAMstrandField intronMotif --outSAMattributes NH HI AS nM NM MD jM jI XS ch --outSAMattrIHstart 0`

Please let me know what other information you need!

Thank you very much,

Nancy

**Comment by ruolin** [comment]
@nancydongxyz Hi Nancy, I have fixed the problem. This problem is caused by uncanonical contig names rather than STAR. The latest version of STAR is totally compatible with Strawberry. Please update your version to 0.9.1 or download the corresponding binary.

**Comment by nancydongxyz** [comment]
Hello Ruolin,

Fantastic, I will give v0.9.1 a try. Thank you very much!

Nancy
