### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by pepap** [ruolin/strawberry#16]
I was not able to install it

==================================
git clone :
==================================
> git clone --recursive https://github.com/ruolin/Strawberry.git
Cloning into 'Strawberry'...
remote: Counting objects: 2065, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 2065 (delta 15), reused 21 (delta 11), pack-reused 2031
Receiving objects: 100% (2065/2065), 36.07 MiB | 82.00 KiB/s, done.
Resolving deltas: 100% (1285/1285), done.
Checking connectivity... done.
Checking out files: 100% (156/156), done.
Submodule 'external/easyloggingpp' (git@github.com:muflihun/easyloggingpp.git) registered for path 'external/easyloggingpp'
Cloning into 'external/easyloggingpp'...
key_load_public: invalid format
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:muflihun/easyloggingpp.git' into submodule path 'external/easyloggingpp' failed
==================================
from scratch :
==================================
> sh cmake.sh
-- The CXX compiler identification is GNU 5.3.0
-- Check for working CXX compiler: /software/gcc/5.3.0/bin/c++
-- Check for working CXX compiler: /software/gcc/5.3.0/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Using g++ complier: /software/gcc/5.3.0/bin/c++
-- Performing Test COMPILER_SUPPORTS_CXX14
-- Performing Test COMPILER_SUPPORTS_CXX14 - Success
Making Release build
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found samtools: /software/ncbr/softrepo/common/samtools/0.1.19/x86_64/single/libbam.a
-- Configuring done
CMake Error at src/CMakeLists.txt:33 (add_executable):
  Cannot find source file:

    /auto/brno2/home/pepap/tmp/strawberry-0.9.1/external/easyloggingpp/src/easylogging++.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: strawberry
CMake Error: Cannot determine link language for target "strawberry".
-- Generating done
-- Build files have been written to: /auto/brno2/home/pepap/tmp/strawberry-0.9.1/build
==================================

**Comment by ruolin** [comment]
@pepap Thank you for the feedback. It is because you have been using the ssh key in your environment. I have changed the submodule to use https server. Let me know if it works. Please do `git clone --recursive ` again.
