### ISSUE TITLE
Strawberry fails on Ensembl .gtf files ?

### ISSUE THREAD

**Issue by flatberg** [ruolin/strawberry#17]
Is strawberry renaming the Ensembl seq names with "chr" prefix ?: My gtf file is standard Ensembl GRCh38 and the bam file is from STAR using the same gtf file.

log:
OUTPUT gtf file: 
test/assembled_transcripts.gtf
see test//tracking.log for the progress of the program 
Has loaded transcripts from 47 Chromosomes/Scaffolds
Warning: the gff file contains seq name chr1 which is not found in the bam file
Warning: the gff file contains seq name chr2 which is not found in the bam file
Warning: the gff file contains seq name chr3 which is not found in the bam file
Warning: the gff file contains seq name chr4 which is not found in the bam file
Warning: the gff file contains seq name chr5 which is not found in the bam file
Warning: the gff file contains seq name chr6 which is not found in the bam file
Warning: the gff file contains seq name chr7 which is not found in the bam file
Warning: the gff file contains seq name chrx which is not found in the bam file
Warning: the gff file contains seq name chr8 which is not found in the bam file
Warning: the gff file contains seq name chr9 which is not found in the bam file
Warning: the gff file contains seq name chr11 which is not found in the bam file
Warning: the gff file contains seq name chr10 which is not found in the bam file
Warning: the gff file contains seq name chr12 which is not found in the bam file
Warning: the gff file contains seq name chr13 which is not found in the bam file
Warning: the gff file contains seq name chr14 which is not found in the bam file
Warning: the gff file contains seq name chr15 which is not found in the bam file
Warning: the gff file contains seq name chr16 which is not found in the bam file
Warning: the gff file contains seq name chr17 which is not found in the bam file
Warning: the gff file contains seq name chr18 which is not found in the bam file
Warning: the gff file contains seq name chr20 which is not found in the bam file
Warning: the gff file contains seq name chr19 which is not found in the bam file
Warning: the gff file contains seq name chry which is not found in the bam file
Warning: the gff file contains seq name chr22 which is not found in the bam file
Warning: the gff file contains seq name chr21 which is not found in the bam file
Warning: the gff file contains seq name chrmt which is not found in the bam file
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 29
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 32
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 35
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 37
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 38
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 40
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 42
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 44
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 48
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 49
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 50
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 51
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 53
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 58
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 60
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 67
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 80
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 82
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 86
Inspecting sample......
Total number of mapped reads is: 2774
Using user specified insert size mean: 200 and standard deviation: 80
GL000195.1	50807	51065 finishes abundances estimation
GL000219.1	88308	99533 finishes abundances estimation
KI270706.1	51497	51702 finishes abundances estimation
KI270734.1	138082	156497 finishes abundances estimation
GL000218.1	51867	54893 finishes abundances estimation
GL000218.1	58353	58552 finishes abundances estimation
GL000218.1	65596	65844 finishes abundances estimation
GL000218.1	66186	66393 finishes abundances estimation
KI270721.1	10908	11802 finishes abundances estimation
KI270711.1	4612	24703 finishes abundances estimation
KI270714.1	9626	9834 finishes abundances estimation
KI270718.1	37809	38051 finishes abundances estimation
Finished in 455372 ms
Program finished

**Comment by ruolin** [comment]
@flatberg hello, thanks for reporting this issue. What is the command line you are using? And if you do not supply gtf, is the result normal? Can you share a few hundred of bam lines with bam header to me?

**Comment by flatberg** [comment]
specific cmd:

>  strawberry -g /ext_db/homo_sapiens/GRCh38/genes.gtf -p 4 -v -o test /projects/GCF-2017-465/tmp/star/3002i.Aligned.sortedByCoord.out.bam

The gtf file is Ensembl (R87): 
[ftp://ftp.ensembl.org/pub/release-87/gtf/homo_sapiens/Homo_sapiens.GRCh38.87.gtf.gz](url)

>samtools view -h /projects/GCF-2017-465/tmp/star/3002i.Aligned.sortedByCoord.out.bam 1:1-200000 | samtools view -Sb | gzip -c > test.bam.gz

(github would not upload .bam, hence the .gz)
[test.bam.gz](https://github.com/ruolin/strawberry/files/1613439/test.bam.gz)

**Comment by flatberg** [comment]
and running without the -g [gtf] option still looks like it fails with 2674 mapped reads (none counted on the normal chr as before).

FYI:
> samtools flagstat /projects/GCF-2017-465/tmp/star/3002i.Aligned.sortedByCoord.out.bam

39063183 + 0 in total (QC-passed reads + QC-failed reads)
6570889 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
39063183 + 0 mapped (100.00% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

**Comment by ruolin** [comment]
@flatberg , thank you very much for providing the test case! I noticed that your test.bam contains only single-end reads and the samtools flagstat also proves that. Currently Strawberry only support paired-end reads. I am starting to implement single-end read feature and I do believe some users like you still need that. However, keep in mind that both assembly and quantification algorithms are designed for paired-end reads. Using single-end reads will for sure hurt the performance.
