### ISSUE TITLE
Usability of Strand-specific RNA-seq Data

### ISSUE THREAD

**Issue by DarioS** [ruolin/strawberry#18]
According to the journal article, the method works for strand-specific reads. However, none of the options specified by the user to the software are for specifying the strand-specific type of sequencing done. For example, StringTie has options `--fr` and `--rf`. Can Strawberry correctly assemble transcripts if they have overlapping genomic coordinates but are on opposite strands?

**Comment by ruolin** [comment]
Hi @DarioS, thanks for reporting. I will fix this during the weekend. Currently, I don't have a proper test case. Do you have a strand-specific bam file that you can share with me? Yes. Strawberry can assemble transcripts on opposite strands. If you can give me the url or send me to `rliu0606@gmail.com`

**Comment by DarioS** [comment]
You might like to use a [publicly available BAM file](https://www.encodeproject.org/files/ENCFF324RIZ/) from ENCODE Project, for instance. You could check genes which are on opposite strands and have largely overlapping 3' UTRs to make sure they are not being assembled into one transcript.

**Comment by ruolin** [comment]
Hi @DarioS thank you for the bam file. I have implemented the Strand-specific options and test against the bam file that you provided. Strawberry is able to assemble overlapping transcripts. Please see https://github.com/ruolin/strawberry/releases/tag/0.9.2
