### ISSUE TITLE
sorting order

### ISSUE THREAD

**Issue by jorgeibarracaballero** [ruolin/strawberry#22]
Hello. I hope you can help me.
I am running a RNAseq experiment. I used tophat to map the reads (single end) to the reference genome (sorghum) including the corresponding gff file ("filtered" using: gffread Sbicolor_454_v3.1.1.gene.gff3 -o Sbicolor_filtered.gff), then I use the bam file from tophat in strawberry. It works fine if I am not including the reference annotation, but it crashes if I include it (the same gff file that I provided to tophat).  I am getting this message (the first part for all 10 chromosomes, there are more extra scaffolds).
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 9
strawberry: /home/ruolin/git/strawberry/include/gff.h:325: int GffTree::get_gseq_id() const: Assertion `!_genes.empty()' failed.
Aborted (core dumped)

 Do you think the problem is that I am working with single end reads?
Also, I noticed that not all the chromosomes (actually, the extra scaffolds) are presented in the gff file, because some have no annotation.
Let me know what you think, please.
Thank you,

Jorge

**Comment by ruolin** [comment]
@jorgeibarracaballero Hi Jorge, 
Thank you for your interests in strawberry. First of all, the single end reads should work fine. From the output it looks like you have a non-standard gff3? Strawberry might be more strict about the rules, but this is something I can fix. Is there a way to share your gff3 and a subset of the bam (including the header) with me?

**Comment by jorgeibarracaballero** [comment]
Hi!
Sure I can share them.
I also tried using the original gff3 file (not "filtered") with same results (after using this file with tophat and then the corresponding .bam file).
How to get a subset of the bam file (with header)? I can try to find out but probably you know how to do it.
I can also try to send you the whole bam file using wetransfer.
Thanks!
Jorge

**Comment by ruolin** [comment]
you can use `samtools view -h your.bam | head -n 10000 > test.sam` and share the test.sam and gff3 with me. My email is rliu0606@gmail.com. You can share with me using google drive or something else. Thanks!

**Comment by jorgeibarracaballero** [comment]
Here is the original gff3 file and a subset of the accepted_hits.bam file that I got using exactly that gff3 file.
I will upload the whole bam file and will send you the link so you can have it if needed.
Thank you!

[Sbicolor_454_v3.1.1.gene.gff3.zip](https://github.com/ruolin/strawberry/files/2545397/Sbicolor_454_v3.1.1.gene.gff3.zip)

[12_test.sam.zip](https://github.com/ruolin/strawberry/files/2545409/12_test.sam.zip)

**Comment by ruolin** [comment]
@jorgeibarracaballero Thank you for providing the files. I ran through the small test case it seems to be fine. Just to confirm that were you using something like this `strawberry 12_test.bam -g Sbicolor_454_v3.1.1.gene.gff3`? And which version of strawberry are you using? It looks like that I need the full bam to debug.

**Comment by jorgeibarracaballero** [comment]
strawberry 12_thout/accepted_hits.bam -o 12_strawberry_out2 -g Sbicolor_454_v3.1.1.gene.gff3 -p 8

the bam file is in the 12_thout folder.

strawberry v1.0.1

I'm going to upload the bam file and will send you a link when it is available
Thank you!

**Comment by jorgeibarracaballero** [comment]
I sent the link to your email: rliu0606@gmail.com

**Comment by ruolin** [comment]
Hi, @jorgeibarracaballero I didn't get the link. Can you send it again?

**Comment by jorgeibarracaballero** [comment]
Oh,
https://we.tl/t-093w2jcaGQ

Enviado desde mi iPhone n+1

**Comment by ruolin** [comment]
@jorgeibarracaballero It is interesting that I don't get any error by running your data. I attached the output from strawberry. I used `strawberry 12_accepted_hits.bam -o 12_strawberry_out2 -g Sbicolor_454_v3.1.1.gene.gff3`. If you use the small bam that you sent to me, do you still have the error?


[assembled_transcripts.gtf.zip](https://github.com/ruolin/strawberry/files/2556182/assembled_transcripts.gtf.zip)

**Comment by jorgeibarracaballero** [comment]
Hi,
I am confused. In your comment here at https://github.com/ruolin/strawberry/issues/22 your command is:
strawberry 12_accepted_hits.bam -o 12_strawberry_out2 -g
without the gff3 file after -g
But in the email that I received, the command is:
strawberry 12_accepted_hits.bam -o 12_strawberry_out2 -g Sbicolor_454_v3.1.1.gene.gff3 -p 8Sbicolor_454_v3.1.1.gene.gff3 -p 8
with a 'repeat' after -p8 without a space
So, I think you mean:
strawberry 12_accepted_hits.bam -o 12_strawberry_out2 -g Sbicolor_454_v3.1.1.gene.gff3 -p 8
the same that I used.
Anyway, I am going to try again and will be back to you.
Thank you

**Comment by ruolin** [comment]
@jorgeibarracaballero Hi Jorge, Sorry about the confusion. When I copied the last part of the command to the dialogue it somehow got deleted. So you are right I used the same as you did and did not have errors. BTW, did you use the binary or you built from the master branch?

**Comment by jorgeibarracaballero** [comment]
$ ../strawberry 12_accepted_hits.bam -o 12_strawberry_out2 -g Sbicolor_454_v3.1.1.gene.gff3 -p 8
Log to file 12_strawberry_out2/execution.log
Has loaded transcripts from 90 Chromosomes/Scaffolds
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 12
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 15
[and so on until:]
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 868
[then it runs the same as when I don't include the -g flag]
Finished in 367374 ms
Program finished

I thought that maybe it worked fine after "set gff chrom id", but then I ran "just do quantification against provided gene models"

$ ../strawberry 12_accepted_hits.bam -o 12_strawberry_out3 -g Sbicolor_454_v3.1.1.gene.gff3 -r -p 8
Log to file 12_strawberry_out3/execution.log
Has loaded transcripts from 90 Chromosomes/Scaffolds
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 12
[and so on until:]
if you use --no-assembly option, you must provide gff file through -g option!
strawberry: /home/ruolin/git/strawberry/src/alignments.cpp:1128: int Sample::nextClusterRefDemand(HitCluster&): Assertion `false' failed.
Aborted (core dumped)

I assumed then then that the program was not really using the gff3 file when run with -g and not -r flag, but maybe it worked?
But it definitely is not working with both -g and -r

Then, I ran using the test.bam (after converting .sam to .bam):
$ ../strawberry 12_test.bam -o 12_strawberry_out2test -g Sbicolor_454_v3.1.1.gene.gff3 -p 8
[Same than with the full .bam file]

$  ../strawberry 12_test.bam -o 12_strawberry_out2test -g Sbicolor_454_v3.1.1.gene.gff3 -r -p 8
[Same than with the full .bam file]

I am using the binary. I wonder if the program is calling samtools. I have installed Version: 1.6

**Comment by ruolin** [comment]
@jorgeibarracaballero Your speculation is right. Your gff3 file has no `exon` field. So Strawberry does not actually use the your gff3. While I am trying to fix this, a quick thing you can try is to replace CDS with exon in your gff3 file by `sed -i 's/CDS/exon/g' Sbicolor_454_v3.1.1.gene.gff3`. And It should work.

**Comment by jorgeibarracaballero** [comment]
Oh, I see.
Thanks, I hope this will be useful for you and strawberry too.
I will try it soon, will let you know.
Jorge

Enviado desde mi iPod n+1

**Comment by jorgeibarracaballero** [comment]
I replaced all "CDS" with "exon", but sorry, it didn't work again. I tried 
strawberry 12_accepted_hits.bam -o 12_strawberry_out3 -g Sbicolor_454_v3.1.1.gene.gff3 -r -p 8
and again got the "Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to ..." messages, then several:
"Chr01	563340	564836 finishes abundances estimation", and then:
"Chr01	526909	strawberry: ../nptl/pthread_mutex_lock.c:79: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
532481 finishes abundances estimation
Aborted (core dumped)"

The results file is empty

**Comment by ruolin** [comment]
@jorgeibarracaballero Sorry about the errors. But again on my end, it works just fine. Can you try two things to help me locate the problems? It seems to be a pthread problem. Can you delete -p 8 to use a single thread? Secondly, can you try to build the strawberry from scratch? It should be easy to build, just follow the instruction from the front page. I can help you if you have any problems to build strawberry.

**Comment by jorgeibarracaballero** [comment]
No worries.

I will try as you say.

Thanks,

Jorge

**Comment by jorgeibarracaballero** [comment]
It worked, using the file with "exon" instead of "CDS" and only one thread, although I still again got the "Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to ..."
messages, but then I kept running and I got an output, both with -r and without.
I will try to build it from scratch

**Comment by ruolin** [comment]
@jorgeibarracaballero These warnings tell that your bam header does not match the gff file. If you check your gff file, some contigs are missing. Strawberry tries it best to warn you that you might use a wrong gff file. But in your case, you probably just don't have them annotated yet and those are very small contigs. Strawberry can still proceed and these warnings have no effect on the results.

**Comment by jorgeibarracaballero** [comment]
Yes, you are right. I got the genome and gff3 file from JGI, they are supposedly the best for sorghum currently,but you are not for all uses.
Thank you for your help!

Enviado desde mi iPhone n+1

**Comment by ruolin** [comment]
@jorgeibarracaballero You are welcome! Your information and data is helpful. I will fix the problem in the next release so that you don't need to replace CDS with exon.
