### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by lietai** [ruolin/strawberry#23]
Hi,

I'am currently working with some synthetic RNA to benchmark some few things from
https://www.nature.com/articles/nmeth.3958

And I got a segmentation fault from one file 
[SegFault.zip](https://github.com/ruolin/strawberry/files/2553670/SegFault.zip)
here are a small fragment of the bam file that will cause a segmentation fault and the associated GTF 
file.
The chrIS do not pause any problem since other sample work perfectly
Best regards.

**Comment by ruolin** [comment]
@47Lies Thank you very much for reporting this bug! I have made a patch and released the new version of strawberry (1.0.2) https://github.com/ruolin/strawberry/releases/tag/1.0.2.
I also updated the master branch. You can check out the front page.

**Comment by lietai** [comment]
@ruolin It works.

Thank you.
