### ISSUE TITLE
Assertion `_assay_props._platform == UNKNOWN_PLATFORM' failed

### ISSUE THREAD

**Issue by TSL-RamKrishna** [ruolin/strawberry#25]
Strawberry fails with following message:
virtual bool HitFactory::parse_header_line(const string&): Assertion `_assay_props._platform == UNKNOWN_PLATFORM' failed

While checking the code, I see it return SoLiD or Illumina and then asserts the return value is equal to UNKNOWN_PLATFORM. I do not get why it is checking if it is equal to UNKNOWN_PLATFORM.

I commented the line in the src/read.cpp file where it asserts _assay_props._platform == UNKNOWN_PLATFORM (line 357 in the file) and recompiled the software. It seems to work then.

**Comment by ruolin** [comment]
@TSL-RamKrishna Thank you very much for suggesting this fix! I will update the code to reflect your suggestions. Since it works for you now, I think I will put this fix into the next release. But let me know if you and any blockers, then I will update it soon. Again, thank you very much!
