### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by shinyanishio** [ruolin/strawberry#26]
Hi. Now I'm in trouble to install Strawberry. Please help!

After I moved into build and run make. But I could not finish installation.

The error message was below
==
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=1 -I. bam_tview_curses.c -o bam_tview_curses.o

bam_tview_curses.c:5:10: fatal error: curses.h: No such file or directory
 #include <curses.h>
          ^~~~~~~~~~
compilation terminated.
Makefile:24: recipe for target 'bam_tview_curses.o' failed
make[4]: *** [bam_tview_curses.o] Error 1
make[4]: Leaving directory '/home/nishio/Strawberry/external/samtools-0.1.19'
Makefile:27: recipe for target 'all-recur' failed
make[3]: *** [all-recur] Error 1
make[3]: Leaving directory '/home/nishio/Strawberry/external/samtools-0.1.19'
CMakeFiles/samtools.dir/build.make:116: recipe for target 'samtools-prefix/src/samtools-stamp/samtools-build' failed
make[2]: *** [samtools-prefix/src/samtools-stamp/samtools-build] Error 2
make[2]: Leaving directory '/home/nishio/Strawberry/build'
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/samtools.dir/all' failed
make[1]: *** [CMakeFiles/samtools.dir/all] Error 2
make[1]: Leaving directory '/home/nishio/Strawberry/build'
Makefile:154: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ruolin** [comment]
Hi @shinyanishio, thanks for using Strawberry. You message says that `curses.h` is missing. What platform are you using? In Linux/Unix, the `curses.h` should be in the system location `/usr/include/curses.h`.

**Comment by shinyanishio** [comment]
Hi ! I tried Ubuntu 16.04LTS and 18.04LTS. I only install gcc, g++, make, git, zlib.

**Comment by shinyanishio** [comment]
Thank you for your comment. I installed libncurses5 to locate curses.h by below command.
sudo apt-get install libncurses5-dev

After installation, Now I can install strawberry! Thank you!

**Comment by ruolin** [comment]
@shinyanishio Thank you very much for suggesting the solution! I will put libncurses5 as one of the dependencies in case of any other users have the same problem.
