### ISSUE TITLE
 `!_genes.empty()' failed.

### ISSUE THREAD

**Issue by MCH74** [ruolin/strawberry#27]
Hi,
I've tried running Strawberry with a gff. 
I needed to sort the gff3 file so that the chromosomes were in the same order as in the sorted bam file (they were in a random order in the gff3).

Then when running:

bin/strawberry sort.bam -o ./  -g sort.gff -p 8

I get the following error:
strawberry: /global/group/home/harrisom/Programs/Strawberry/include/gff.h:325: int GffTree::get_gseq_id() const: Assertion `!_genes.empty()' failed.
Aborted (core dumped)

Any ideas what can be causing this?

Thanks,
Mark

**Comment by ruolin** [comment]
Hi @MarkChristianHarrison Sorry about the late reply. Can you check if your gff3 file has `exon` field? I have another user that has the same error and don't have the `exon` field. See #22

**Comment by MCH74** [comment]
Hi Ruolin,
Yes my gff has gene, exon and cds fields. But I had to change the gff for the scaffolds to be in the same order as the bam file. Maybe that created problems? Now CDS and EXON features alternate:

scf00001 maker gene ....
scf00001 maker mRNA ...
scf0001 maker exon ...
scf0001 maker CDS ...
scf0001 maker exon ...
scf0001 maker CDS ...
scf0001 maker exon ...
scf0001 maker CDS ...
 ....

Could this be causing the problem? 

Thanks,
Mark

**Comment by ruolin** [comment]
@MarkChristianHarrison Hi, you don't need to change the scaffolds to be in the same order. Strawberry will do that and the reason that I give out the warning is that some users might use a wrong gff file. If you believe your gff is correct, you don't need to sort them. Can you try with the original gff file? It the problem still exists can you send me your gff file with your bam?
