### ISSUE TITLE
How to merge multiple .gtf files

### ISSUE THREAD

**Issue by crj32** [ruolin/strawberry#29]
Hi, thanks for strawberry, cool name.

But how do I merge multiple .gtf files from each BAM sample like stringtie does? Is this an option? 

Like this:
https://github.com/griffithlab/rnaseq_tutorial/wiki/Transcript-Assembly-Merge

Best wishes,

Chris

**Comment by ruolin** [comment]
@crj32 Thank you for your comment. I guess, stringtie merge should also work for strawberry output gtfs.
Otherwise, cuffmerge http://cole-trapnell-lab.github.io/cufflinks/cuffmerge/ is what I use to merge multiple .gtf files.
