### ISSUE TITLE
Bug/s in version 1.0.8

### ISSUE THREAD

**Issue by crj32** [ruolin/strawberry#36]
This new version looks promising, but I get the following errors:

## throws an error

strawberry SAM24297965.bam -p 20 -g ./gencode.v29.annotation.gtf -o ./test.gtf

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

## throws an error

strawberry SAM24297965.bam -p 20 -g gencode.v29.annotation.gtf -o test.gtf

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by ruolin** [comment]
Sorry about that. Can you share me your bam so I can fix the bug/s. My email is rliu0606@gmail.com.

**Comment by ruolin** [comment]
@crj32 It took me a quite a while to pinpoint the mem bugs, quite hidden ones.  Thank you for reporting and sharing the file. Let me know how does it go with https://github.com/ruolin/strawberry/releases/tag/1.1.0. And I will delete the file once you run it through.

**Comment by crj32** [comment]
Sorry Ruolin I'm going to be busy for quite a while with other projects, but I guess everything is working now and we have made Strawberry considerably more appealing for other users. Thanks for your help with this.

**Comment by ruolin** [comment]
No problem. Thank you for your comments and suggestions. I really appreciate it.

**Comment by ruolin** [comment]
@crj32 I will close this issue for now. Feel free to reopen it.
