### ISSUE TITLE
Segmentation fault when output directory for log file parameter is missing

### ISSUE THREAD

**Issue by petersbr** [ruolin/strawberry#37]
Hello ,

This is a suggestion to add some basic parameter validation so that it is easier to figure out what is wrong with command calls.  Receiving a segmentation fault is much harder to interpret that: something like "Specified output directory X is missing" or just creating it on the fly.  

In my case I was passing "--logfile logs/strawberry.log" but "logs" didn't exist and I just received a segfault.

Thanks

**Comment by ruolin** [comment]
Hi, 
Thank you for your suggestion. I have fixed it in the version 1.1.1.
