### ISSUE TITLE
never endig processes

### ISSUE THREAD

**Issue by moxgreen** [ruolin/strawberry#38]
Hi,
I'm using  strawberry v1.1.1 whit the following command line
`
strawberry sorted.bam -o strawberry.gtf -T strawberry.gtf.log -g ref_annot.gtf -p 6
`
The process reached 100% of CPU but not more, as expected due to -p 6, and I let it run at 100% CPU for several days. Both `strawberry.gtf` and `strawberry.gtf.log` have some data, stderr shows
```
OUTPUT gtf file: 
strawberry.gtf
see strawberry.gtf.log for the log of the program 
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 13
Warning: Sam file and Gff file are not sorted in the same order!
set gff chrom id to 21
Has loaded transcripts from 27 Chromosomes/Scaffolds
```. 
but the process do not end.

Have you any hint to debug this situation?
Can you provide a docker image to test in a controlled environment?

Thanks

**Comment by ruolin** [comment]
Hi, thanks for reporting this issue. I will put a docker image. By the meantime, it may not fix the problem. Would you like to provide your bam for me so I can root cause it?

Thanks

**Comment by ruolin** [comment]
@moxgreen I have dockerized the application. Please do `docker pull ruolinliu/strawberry:v1.1.1` and refer to the readme for more information. Let me know if this works for you

**Comment by moxgreen** [comment]
Thanks, I will try asap.
