### ISSUE TITLE
--allow-multimapped-hits generate partial coverage

### ISSUE THREAD

**Issue by daniel-es6** [ruolin/strawberry#39]
Hi Ruolin,

I am trying to use Strawberry to do some RNAseq isoform analysis if targeted sequencing and got a question that I could not figure out. The --allow-multimapped-hits switch seems to affect the isoform results a lot. In some cases, the default (without --allow-multimapped-hits) will generate isoforms that lack coverage of regions with a lot of reads, but the results from runs with --allow-multimapped-hits will generate isoforms with complete coverage. In other cases, the situation is just the opposite. I have attached some slides here. 

I used tophat2 and bowtie2 to do the alignments. In both cases, the amount of multialigned reads are very small, (<0.1%). In the slides, shaded areas are the read coverages.
Any help or advice  is greatly appreciated. 

[straberry diagnosis.pptx](https://github.com/ruolin/strawberry/files/4130487/straberry.diagnosis.pptx)

-Daniel

**Comment by ruolin** [comment]
Hi Daniel,  

Thanks for posting the issue. Strawberry relies on an additional tag for finding the hits with multiple alignments. It might be different from what you got from the flag for secondary alignments. Can you first confirm your bam has `NH` tag?
