### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by sum732** [ruolin/strawberry#41]
Hi,
I am trying to build and keeping running into following message:
```Making Release build
-- Could NOT find ZLIB (missing:  ZLIB_LIBRARY) (found version "1.2.3")
CMake Error at CMakeLists.txt:99 (message):
  zlib must be installed before configuration & building can proceed
```` 
Where as ```zlib/1.2.8``` is available and in path 
Any suggestions to fix the issue will be appreciated. 
Thanks.

**Comment by ruolin** [comment]
It seems like you have two versions of ZLIB installed. The cmake module might found it confusing. Can you try setting `ZLIB_INCLUDE_DIR` and `ZLIB_LIBRARY` with environment variables and as -D parameters to CMake

Another way is to just use the docker image or the compiled binary.
