### ISSUE TITLE
Problem with gtf file

### ISSUE THREAD

**Issue by LiuJJ0327** [ruolin/strawberry#42]
Hi, I downloaded hg19 gtf file from UCSC gene brower and used -g option in strawberry, however I get the same problem as issue #20 

error information:
strawberry: /root/strawberry/src/alignments.cpp:1859: double compute_doc(uint, uint, const std::vector<Contig>&, std::vector<float>&, IntronMap&, uint): Assertion `gf.right() >= gf.left()' failed.

I saw it may caused by a one bp intron in the gtf file and has been fixed in 0.9.3. However I implement the latest version 1.1.1 and still had this problem.
Can you give me any idea?

**Comment by ruolin** [comment]
@LiuJJ0327 Thanks for reporting the bug. I have updated the master branch to `c2a4640`. Could you try this version?

**Comment by LiuJJ0327** [comment]
I tried latest version, but new error exist. Please see below.

Has loaded transcripts from 25 Chromosomes/Scaffolds
strawberry: /root/strawberry/src/alignments.cpp:322: void HitCluster::addRefContig(const Contig&): Assertion `_ref_id == contig.ref_id()' failed.
Aborted

**Comment by LiuJJ0327** [comment]
> @LiuJJ0327 Thanks for reporting the bug. I have updated the master branch to `c2a4640`. Could you try this version?

I tried latest version, but new error exist. Please see below.

Has loaded transcripts from 25 Chromosomes/Scaffolds
strawberry: /root/strawberry/src/alignments.cpp:322: void HitCluster::addRefContig(const Contig&): Assertion `_ref_id == contig.ref_id()' failed.
Aborted

**Comment by ruolin** [comment]
Can you check if your gft file has the same chromosome id as is in your bam file? The typical theme here in one file you have `chr` and the other does not.

**Comment by LiuJJ0327** [comment]
> Can you check if your gft file has the same chromosome id as is in your bam file? The typical theme here in one file you have `chr` and the other does not.

I tested using: **_strawberry  test.bam -o test_out.gtf -g hg19_sed.gtf -p 8_**
but still get the same error. test.bam and hg19_sed.gtf have same chromosome.
My real bam file is H1_rep1.bam. Can you help me to figure out the problem? Below is my data. Thank you so much.

https://drive.google.com/file/d/1muxvaxDc3ZGMG0pR-e2iTVvlBUMkNLfT/view?usp=sharing
https://drive.google.com/file/d/1ZUDjn0yrMQauLdtIQtkdFjfnLNX5IoZ7/view?usp=sharing
https://drive.google.com/file/d/1VDugrDHMDG0hAeUhC_rRxXEqiyhkqQaf/view?usp=sharing

**Comment by ruolin** [comment]
@LiuJJ0327 Again, thanks for sharing the test data. After awhile, I found out this corner case is causing the problem
```
64526:chr1	hg19_refGene	exon	17369	17436	.	-	.	gene_name "MIR6859-3"; gene_id "NR_107063"; transcript_id "NR_107063";
409818:chr15	hg19_refGene	exon	102513727	102513794	.	+	.	gene_name "MIR6859-3"; gene_id "NR_107063"; transcript_id "NR_107063";
461414:chr16	hg19_refGene	exon	67052	67119	.	-	.	gene_name "MIR6859-3"; gene_id "NR_107063"; transcript_id "NR_107063";
```

As you can see, a gene is located on two different chromosomes. I fix this issue in v1.1.2. I have tested the new version on your input data and it works fine.

**Comment by ruolin** [comment]
@LiuJJ0327 Does the new version work for you?

**Comment by LiuJJ0327** [comment]
> @LiuJJ0327 Does the new version work for you?

Yes. Thank you so much.
