### ISSUE TITLE
Understanding of parameter --max-junction-splice-size

### ISSUE THREAD

**Issue by sanyalab** [ruolin/strawberry#44]
Hello,

This is not an issue. But I wanted to understand if "--max-junction-splice-size" parameter refers to max intron length. Similarly "--min-junction-splice-size" refers to minimum intron length.

Thanks
Abhijit

**Comment by ruolin** [comment]
You are right. This is the max intron size since some aligners sometimes falsely output splice alignment with junction size too big to be true.

**Comment by sanyalab** [comment]
Ok. Super. Thank you.
